### ISSUE TITLE
[SOS] Create FOIs list endpoint accepting filter by id

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-contribs#163]
For FOIs we also need the list endpoint to let the client obtain a list of FOIs given their IDs.

@mattiagiupponi I don't know if the filters provided Dynamic REST support a compact way to send the IDs (e.g. `?filter{name.in}=1,2,3,4`). If the filter must be repeated it might become pretty long in case the WMS GFI returns a long list of features.
An alternative might be to use a POST with the list of IDs sent inside the JSON body.

**Comment by mattiagiupponi** [comment]
@giohappy No, dynamic rest doesn't provide this feature
I suggest instead using the GET and passing the IDs as a payload and creating a custom filter inside the `filter_backends`. Passing a body to a GET request is acceptable since is out endpoint:

>  A payload within a GET request message has no defined semantics;
>    sending a payload body on a GET request might cause some existing
>    implementations to reject the request.

Ref: https://www.rfc-editor.org/rfc/rfc7231#page-24
